spring:
  application:
  name: movie-ticket-booking-system-api
  datasource:
    url: jdbc:mysql://localhost:3306/mtb?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
